name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: colorama.sh
      run: ./colorama.sh
      
    - name: Install dependencies
      run: make install
      
    - name: Run check
      run: make install
      
    - name: Run update
      run: make update
