name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: makefile
      run: make uninstall
      
    - name: Install dependencies
      run: make install
      
    - name: Run check
      run: make update
      
    - name: Run distcheck
      run: make distcheck
